apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-multi-ecr-credentials.serviceAccount" . }}
  labels:
{{ include "aws-multi-ecr-credentials.labels" . | indent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role
  labels:
{{ include "aws-multi-ecr-credentials.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - serviceaccounts
      - serviceaccounts/token
    verbs:
      - 'delete'
      - 'create'
      - 'patch'
      - 'get'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role-binding
  labels:
{{ include "aws-multi-ecr-credentials.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-multi-ecr-credentials.serviceAccount" . }}
#    namespace: {{ .Values.targetNamespace }}
